image: /home/tas_group_10/catkin_ws/src/tas_car/tas/launch/config/map_server/map.pgm
resolution: 0.050000
origin: [-25.624998, -25.624998, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

